[build]
  command = "npm install && npm run build"
  publish = "dist"
  functions = "functions"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
  force = false

[[redirects]]
  from = "https://placekeanu.netlify.com/*"
  to = "https://placekeanu.com/:splat"
  status = 301
  force = true