[build]
  command = "npm install && npm run build"
  publish = "dist"
  functions = "functions"

[[redirects]]
  from = "https://placekeanu.netlify.com/*"
  to = "https://placekeanu.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/"
  to = "/"
  status = 200
  force = false

[[redirects]]
  from = "/keanus"
  to = "/keanus"
  status = 200
  force = false

[[redirects]]
  from = "/error"
  to = "/error"
  status = 200
  force = false

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/svg-generator/:splat"
  status = 200
  force = false
